# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: YK crew
name: YKcrew
email: sweetyangkun@gmail.com
location: Cleveland, U.S.
company: Case Western Reserve University
#company_url: http://ykcrew.com
github_url: https://github.com/xixinxin
description: This is personnel website of YKcrew, Courtesy of original author DONGChuan (dongchuan55@gmail.com)
favicon: favicon.png # Image must be in assets/images

url: http://xixinxin.github.io # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home
    
  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: MRI Research
    
  -
    href: /open-source
    label: Resource

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'


# For about.html. 
skill_software_keywords: [Matlab, C++, C, OOD, Design Patterns]
skill_mri_keywords: [Fast Reconstruction, Compressed Sensing, MRF]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [IOS, Android, Sketch UI Desgin]